# Generated by Django 5.2.4 on 2025-08-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate')], max_length=20, null=True),
        ),
    ]
