# Generated by Django 5.2.4 on 2025-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
    ]
