# Generated by Django 5.2.4 on 2025-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
