services:
  backend:
    build: .
    container_name: backend
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - .:/app                # mount into /app
    working_dir: /app/backend # where manage.py & backend package live
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${mongo_uri}

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
