# Generated by Django 5.2.4 on 2025-07-15 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_questionanswerpair_qapair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
